### ISSUE TITLE
Website broken: not allowed access to tileserver

### ISSUE THREAD

**Issue by peterdesmet** [gbif/species-population#5]
The species-population tool at http://gbif.github.io/species-population/frontend/dist/ does no longer display a map. If you open Chrome Dev Tools, you'll see many `XMLHttpRequest` errors for the tileserver.

**Comment by MattBlissett** [comment]
The tool is now integrated in the demo portal: https://demo.gbif.org/tools/species-population

@timrobertson100, can we redirect from the Github demo site?

**Comment by peterdesmet** [comment]
Would be nice if you would just include a prominent link in the README to:

- URL of new tool
- Source code of new tool

**Comment by MattBlissett** [comment]
I've added these to the readme, and set up the redirect.

**Comment by peterdesmet** [comment]
👌 Redirect takes a couple of seconds to kick in, but it works!
